# https://gohugo.io/getting-started/configuration/

baseURL: "https://cedric.hothanh.fr"
defaultContentLanguage: en
enableEmoji: true # https://www.webfx.com/tools/emoji-cheat-sheet/
enableRobotsTXT: true
hasCJKLanguage: true
languageCode: en-us
theme: PaperMod # https://github.com/adityatelange/hugo-PaperMod
title: "Cédric HT"

params:
  profileMode:
    enabled: true
    title: "👋"
    subtitle: "Welcome to my website"
  socialIcons:
    - name: github
      url: https://github.com/altaris
    - name: linkedin
      url: https://www.linkedin.com/in/cedrichothanh
